### ISSUE TITLE
Cannot update offline folders...

### ISSUE THREAD

**Issue by dusrdev** [meganz/android#152]
## General Information

- **MEGA Version:** 4.2.1

- **OS Version(s):** Android 11

- **Devices/Simulators:** Galaxy S10

- **Reproducible? (Yes/No):** Yes

##  What happened? 
when you have a folder which is available offline, even if there are newer files in that folder in the cloud, it is impossible to download them for offline use. The folder is already marked offline so to cache the files I will need to turn it off and on again (meaning it will delete all of the offline folder and redownload) which takes enormous amounts of time instead of just updating and downloading only the new files...
...

## What did you expect to happen?
That I will be able to press on the folder download offline again, then it will try to download the files while checking if they are available thus just downloading the newer files (Exactly as it happens in the iOS)
...

**Comment by javiergm1983** [comment]
Hi @dusrdev , this is not an issue but maybe something to improve. Take into account that the offline section behaviour is slightly different between iOS and Android due some OS restrictions. And this is not a sync feature.

As you can see, in iOS there is no "Save for Offline" option and only have the "Download" option. This is because due some OS restrictions they cannot save files out of the local app space, so the downloads are saved in the offline section.

On the other hand, Android allows save file out of the app local space in the internal storage or external storage (SD card), which is the same as iOS but you can select where you wanto to save the files. If you use the "Download" feature, and tries to download the same folder with updated files you can check that the app should only download the files that had not been previously dowloaded, like iOS does.

In addition the Android app has this "Save for Offline" option which is a feature to save the selected files into the local app space and allow you access them using the MEGA app even when you are not connected to the Internet, but as I said in the first paragraph it is not a sync feature.
We appreciate your report and are planning to add some sync to this feature in the future but for now you only can manually and individually save for offline the new files added to the folder.
