### ISSUE TITLE
same as playstore

### ISSUE THREAD

**Issue by Fazzuliyat** [meganz/android#173]
## General Information

- **MEGA Version: 5.5

- **OS Version(s): android 11

- **Devices/Simulators: xiaomi note 8

- **Reproducible? (Yes/No):** 

##  What happened?
I installed the cracked version but it's same as the normal play store mega. I thought I have to make a purchase in order to get more storage but it only shows purchase amount 0 but not responding when I click on it.

## What did you expect to happen?
I expected more storage but got literally nothing.

**Comment by sakethv-mega** [comment]
Hello, we are not clear with your issue. Can you please tell us what exactly your issue is? And also, why did you install the cracked version instead of downloading the official app from Playstore?

**Comment by WMCB-Tech** [comment]
You can't get more storage from some cracked APKs. you have to actually pay them and is tied to your account

**Comment by RaSan147** [comment]
> ## General Information
> * **MEGA Version: 5.5
> * **OS Version(s): android 11
> * **Devices/Simulators: xiaomi note 8
> * **Reproducible? (Yes/No):**
> 
> ## What happened?
> I installed the cracked version but it's same as the normal play store mega. I thought I have to make a purchase in order to get more storage but it only shows purchase amount 0 but not responding when I click on it.
> 
> ## What did you expect to happen?
> I expected more storage but got literally nothing.

well i think you thought that this place is where the cracked app is being developed. sorry to say, this is MEGA official github repository. so you won't find anything magical like free 5TB account crack here. (by the way, they don't exist at all because your storage capacity has nothing to do with the cracked app as they are handled by the server, not the app) So be rational and use the official App (cracked one's are nothing but the official app with malicious wrapper that can harm your device and data)

**Comment by PJFonseca** [comment]
Hey @javiergm1983, just close this issue.

**Comment by javiergm1983** [comment]
Closed because it refers to a cracked APK and not to the official app.
