### ISSUE TITLE
[Feature request] Change download path

### ISSUE THREAD

**Issue by iTrooz** [meganz/android#190]
- **MEGA Version:** 6.8.1 (436)

I think it would be nice to have an option to change the download path of the files. Currently, it is forced to be `Download/MEGA Downloads/`.
I was thinking about an option in "File Management" to change that directory (For example, I'd like to use `Download` simply), or maybe a toggle "download in separate directory" (to allow users to download directly in the `Download` folder)

I'm willling to submit a pull request for this, if I have your approval

What do you think ?

**Comment by javiergm1983** [comment]
Hi @iTrooz, thanks for your request but we have been forced to do it in this way for Android 11+ devices due Google restrictions for using the `MANAGE_EXTERNAL_STORAGE` permission.

To allow the behaviour that you describes in Android 11+ devices, we would need to use that permission but Google rejected our app arguing that our app is not one of the kinds of apps that they consider valid in order to grant use that permission, so for that reason we are not be able to offer that option for Android 11+ devices and the download path is the default one `Download/MEGA Downloads`.

I will close the request because as I explained before it is not possible to add this behaviour for now.
Thanks for your understanding.
